ruby '2.1.4'
source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'sequel'
gem 'json'
gem 'haml'
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'
gem 'mustache'
gem 'sinatra-flash', :require => 'sinatra/flash'
gem 'sinatra-redirect-with-flash', :require => 'sinatra/redirect_with_flash'
gem 'sinatra-contrib', :require => [ 'sinatra/contrib', 'sinatra/config_file' ]
gem 'mysql2', '~> 0.3.16'
gem 'sqlite3'
gem 'netaddr'
gem 'puma'
gem 'rack-utf8_sanitizer'
gem 'rack-protection'
gem 'builder'
